#!/bin/bash
d=`dirname $0`

ln -s $d/.bashrc ~/.bashrc
ln -s $d/.gitconfig ~/.gitconfig
ln -s $d/.git-completion.bash ~/.git-completion.bash
ln -s $d/.git-prompt.sh ~/.git-prompt.sh
ln -s $d/.eslintrc ~/.eslintrc
ln -s $d/.vim ~/.vim
ln -s $d/.vimrc ~/.vimrc

echo '. ~/.bashrc' >> ~/.bash_profile
